name: openshelf
description: "Biblioteca personal local y FOSS."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado
  flutter_riverpod: ^3.3.1

  # Base de datos local
  drift: ^2.20.0
  drift_flutter: ^0.3.0

  # Escáner ISBN
  mobile_scanner: ^7.2.0

  # API Open Library
  http: ^1.2.2

  # Iconos
  cupertino_icons: ^1.0.8

  # Selector de imágenes
  image_picker: ^1.1.2

  # Ruta de almacenamiento de la app
  path_provider: ^2.1.4

  # Copiar/mover archivos
  path: ^1.9.0

  shared_preferences: ^2.3.0

  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.20.0

flutter:
  uses-material-design: true